### ISSUE TITLE
(new feat/proposal) Assert missing wired props/methods

### ISSUE THREAD

**Issue by fefo-p** [christophrumpel/missing-livewire-assertions#14]
In `Christophrumpel\MissingLivewireAssertions\CustomLivewireAssertionsMixin.php` would be nice to have the opposite functions to test that a property/method is NOT wired. This can happen under several conditions, one being a form that will be loaded according to a property's value.

A working solution for this would be to add another method that asserts it does not match the RegExp given, such as:

```php
public function assertPropertyNotWired(): Closure
    {
        return function (string $property) {
            PHPUnit::assertDoesNotMatchRegularExpression(
                '/wire:model(\.(defer|(lazy|debounce)(\.\d+?(ms|s)|)))*=(?<q>"|\')'.$property.'(\k\'q\')/',
                $this->stripOutInitialData($this->lastRenderedDom)
            );

            return $this;
        };
    }
```

The same could be made available for every assertion method using `PHPUnit::assertMatchesRegularExpression`

**Comment by fefo-p** [comment]
Addressed in pull request #15

**Comment by christophrumpel** [comment]
Hey, thanks for the PR and the feature suggestion. Can you explain to me again when this would be useful to check? I did not fully understand the form example.

**Comment by fefo-p** [comment]
Thanks for replying.
The idea is the following:
- I have a form with a dropdown. Depending on the value selected in that dropdown, I show one or another extra form with different properties wired to a Livewire component.

- That functionality is dependent on the company's business logic.

So in order to test that functionality, I need to be able to assert that properties from the second (extra) form are shown when certain conditions are met. And, that the ones corresponding to the first (extra) form are not.

**Comment by christophrumpel** [comment]
Ah ok, now I got it. Thanks, yeah sounds useful 👍

**Comment by fefo-p** [comment]
Great! Thanks
