### ISSUE TITLE
Livewire 3

### ISSUE THREAD

**Issue by joshualukecaine** [christophrumpel/missing-livewire-assertions#20]
Hey, firstly thanks for the great package.

I started a project recently using Livewire 3 and noticed that the assertions don't work there. 

I have fixed the package locally so that it all works with Livewire 3. Can I make a PR or something? when I try to on Github Desktop I get an error.

![image](https://github.com/christophrumpel/missing-livewire-assertions/assets/25837573/7cb6df55-c8d0-4558-a66c-1a547e0ddf64)

Apologies if this is silly question, first time attempting to contribute to anything like this.

**Comment by christophrumpel** [comment]
Hey, first thanks 🙏

Second, hmm are you sure this is on my side? 🤔 There have been Pull Requests before to this project.

**Comment by joshualukecaine** [comment]
you are right, I had to create a fork first!
