### ISSUE TITLE
Livewire Testable not found

### ISSUE THREAD

**Issue by tom-sk** [christophrumpel/missing-livewire-assertions#25]
```
Class "Livewire\Features\SupportTesting\Testable" not found

 at vendor/christophrumpel/missing-livewire-assertions/src/MissingLivewireAssertionsServiceProvider.php:19
     15▕     }
     16▕
     17▕     public function bootingPackage(): void
     18▕     {
  ➜  19▕         Testable::mixin(new CustomLivewireAssertionsMixin());
     20▕     }
     21▕ }
     22▕

```

Error when installing package in latest Laravel Jetstream install.

**Comment by christophrumpel** [comment]
Hey, is your JetStream installation already using Livewire 3?

**Comment by tom-sk** [comment]
Yeah I think it is. I just installed the latest Jetstream, which I assume is using Livewire 3?

I did see that there was a PR that was trying to fix this: https://github.com/christophrumpel/missing-livewire-assertions/pull/21

**Comment by christophrumpel** [comment]
Hey, just gave it a try with a fresh JetStream installation, and it works for me.

This class does not exist `Livewire\Features\SupportTesting` on your app, which comes from Livewire 3.

Can you check in your `comoser.json` file which Livewire version is being used?

**Comment by tom-sk** [comment]
Thanks for getting back to me, I changed `"livewire/livewire": "*"` to `"livewire/livewire": "^3.0.10"` which I think might of fixed the issue?

Either its working now!
