### ISSUE TITLE
assertMethodWired for action with params/args does not work or not documented

### ISSUE THREAD

**Issue by dostrog** [christophrumpel/missing-livewire-assertions#7]
What is right syntax to check action with params?
```
<x-jet-danger-button type="button" wire:click="deleteConfirm({{$id}})" >
```
This one does not catch
```
$component->assertMethodWired('deleteConfirm');
```

**Comment by christophrumpel** [comment]
Hey @dostrog,

thanks for the update. Params are not supported yet. Could you do a PR for that?

**Comment by dostrog** [comment]
Yeah, sure

[PR to resolve issue#7](https://github.com/christophrumpel/missing-livewire-assertions/pull/8)
